.TH WANSIMSETUP "8" "2.0.1" "Ferry Hendrikx"
.SH NAME
wansimsetup \- Program that controls WANSIM configuration parameters.
.SH "SYNTAX"
.LP
.B wansimsetup
.SH DESCRIPTION
wansimsetup manipulates the configuration information used by WANSIM. It
provides a simple menu interface that allows you to alter any of the 
emulated WAN parameters, including bandwidth (in kbit/s), latency and
jitter (in ms).
.SH SEE ALSO
.BR wansim (8)
.LP
Homepage: http://wansim.googlecode.com/
.SH AUTHOR
WANSIM was developed by Ferry Hendrikx <ferry.hendrikx@gmail.com>.
.PP
This manual page was written by Ferry Hendrikx for the WANSIM project, 
and may be used by anyone.
